version: '3.6'
services:
  application1:
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  application2:
    build: ./service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp